import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Footer from './components/sections/Footer';
import AosProvider from './components/AosProvider';
import Header from './components/sections/Header';
import MainLayoutWrapper from './components/MainLayoutWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AosProvider>
          <Header />
          <MainLayoutWrapper>{children}</MainLayoutWrapper>
          <Footer />
        </AosProvider>
      </body>
    </html>
  );
}
